# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bipin Ghimire
user_description: I am a Data Engineer and Machine Learning Enthusiast with expertise in data processing, cloud technologies, and programming. My passion lies in solving complex problems and leveraging technology to drive impactful insights. With a strong foundation in Python, SQL, and scalable data pipelines, I strive to continuously learn and innovate in the field of data science and engineering.
email: bipin.ghimire692@gmail.com
# twitter_username: lorem_ipsum
github_username:  https://github.com/Bipin38
linkedin_username:  https://www.linkedin.com/in/bipin-ghimire-5587311b0/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
